### ISSUE TITLE
i have error. what i need to do?

### ISSUE THREAD

**Issue by MrVitalii** [antzsmt/ClashLand#2]
1>------ Build started: Project: ClashLand, Configuration: Debug Any CPU ------
1>E:\Downloads\ClashLand-master\ClashLand-master\src\MAGIC\ClashLand.csproj(1200,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Joveler.ZLibWrapper.1.2.0\build\net45\Joveler.ZLibWrapper.targets.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by GhostNaix** [comment]
Use The nuget package manager and restore the packages

**Comment by jakovmarkovanovic** [comment]
Nuget packet reseture
